export const projects = [
  {
    title: "Jack's Blog",
    description: "This is a web application I built for a writer as a space to have all their work, it is a fully responsive full stack application that utilises the MERN stack and implements Auth0 and Formspree",
      image: "/images/Jack's Blog.svg",
      tags: ['React', 'MongoDB', 'Express', 'Node'],
    source: 'https://jacks-blog-frontend.herokuapp.com/posts',
    visit: 'https://github.com/Andrewmoo/Jacks-Blog',
    id: 5,
  },
  {
    title: 'Countries API App',
    description: "This app was developed as a coding task for a job interview. the task was to develop a web app centred around data from the Rest Countries API, the spec sheet called for a minimum of 2 pages 1) [A list of all countries where each country should show at a minimum the following information: Name, Flag, Population] and 2) [A detailed view of each country that displays the following data: flag, name, capital, currency, population, languages for the country.] Additional requirements included usage of the Axios/Fetch API, full responsivness, usage of React and avoiding of design frameworks such as material UI or Bootstrap",
      image: '/images/countriesapp.png',
      tags: ['React', 'Axios', 'React Router DOM', 'Node'],
    source: 'https://csb-2erq4.netlify.app/',
    visit: 'https://codesandbox.io/s/countries-app-2erq4?file=/src/App.js',
    id: 4,
  },
  {
    title: 'Lee Campbell Perrie Portfolio',
    description: "This is a portfolio website I made for an artist friend of mine. it is a fully responsive professional portfolio built using - React, React Hooks, Styled Components, Swiper.js, React Transition Group, React Icons, React Router DOM and more..",
      image: '/images/LeePortfolio.png',
      tags: ['React', 'Swiper.js', 'React Router DOM', 'Node'],
    source: 'https://leecampbellperrie.netlify.app/',
    visit: 'https://github.com/Andrewmoo/Lees-React-Portfolio',
    id: 0,
  },
  {
    title: 'Delaunay Triangulation',
    description:"Phone case patterns designed and coded in P5.JS using a mathematical function called Delaunay triangulation which invloves ensuring no triangle lays inside the circumcircle of any other triangle to achive this computationally I employed the Bowyer Watson algorithm. I really liked the end product and thought the pattern would fit well on phone cases so from there I produced and marketed the cases",
    image: '/images/2.png',
    tags: ['P5.js', 'JavaScript'],
    source: 'https://andrewmoo.github.io/Creative-Coding/Shape-Pattern/Main%20Exercises/Wrapping%20Paper%20Design/index.html',
    visit: 'https://codepen.io/andrewmoo98/pen/YzpBarx?editors=0010',
    id: 1,
  },
  {
    title: 'Stopover',
    description: "Stopover was a project that was part of the the Professional Practice Module in the third year of B.Sc. in Creative Computing. The main goal of the project was to build a functional hotel booking website using the Laravel php framework and mySQL the site would allows users to view, compare and book hotel rooms and allow hotel managers to add, remove and edit listings for rooms in their hotels.",
      image: '/images/3.jpg',
      tags: ['Laravel', 'PHP', 'MySQL'],
    source: 'https://floating-sands-60439.herokuapp.com/',
    visit: 'https://github.com/Andrewmoo/Stopover',
    id: 2,
  },
  {
    title: 'Brownian Motion',
    description: "With this project I wanted to create a generative agent that would swarm seemingly randomly but eventually come together to form text on the screen. Initially after researching and getting interested in flow fields the idea was to use flowfields or some other particle effect to create agents that would zip around and after a certain amount of time it would become apparent they were forming words. After doing research on the different types of agency and particle physics that would fit within the scope of this project I decided on Brownian motion.",
    image: '/images/4.jpg',
    tags: ['P5.js', 'JavaScript'],
    source: 'https://andrew-bell-portfolio.web.app/EOY-Project/index.html',
    visit: 'https://github.com/Andrewmoo/Creative-Coding/blob/main/EOY-Project/sketch.js',
    id: 3,
  },
  {
    title: 'Recommender System',
    description: "A recommender system developed alongside my thesis as an exploration of machine learning. The fundamental reasoning behind picking this project was to develop an extensive knowledge of machine learning, a topic not covered extensively in our course curriculum. While many recommender systems already exist and are widely used within the entertainment industry it is not about the application itself and more about the research and implementation of a new area of knowledge not guided by the course.",
    image: '/images/6.jpg',
    tags: ['Python', 'SciKit-Learn', 'NumPy'],
    source: 'https://andrew-bell-portfolio.web.app/Andrew%20Bell-N00160591-Thesis.pdf',
    visit: 'https://andrew-bell-portfolio.web.app/Better%20recommender.html',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey', },
  { year: 2018, text: 'Worked on personal projects and interests', },
  { year: 2019, text: 'Embraced my passion for web design and development', },
  { year: 2020, text: 'Began writing my thesis and finishing my degree', },
  { year: 2021, text: 'Started working as a freelance web developer', },
];